# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: setup r-reticulate venv
        shell: Rscript {0}
        run: |

          path_to_python <- reticulate::virtualenv_create(
            envname = "r-reticulate",
            python = Sys.which("python"), # placed on PATH by the setup-python action
            packages = c(
              "wheel", "saspy", "pandas"
            )
          )

          writeLines(sprintf("RETICULATE_PYTHON=%s", path_to_python),
                     Sys.getenv("GITHUB_ENV"))

      - name: setup saspy
        env:
          SAS_ODA_USERNAME: ${{ secrets.SAS_ODA_USERNAME }}
          SAS_ODA_PASSWORD: ${{ secrets.SAS_ODA_PASSWORD }}
        run: |
          oda_username = Sys.getenv("SAS_ODA_USERNAME")
          oda_password = Sys.getenv("SAS_ODA_PASSWORD")
          cat(paste("oda user", oda_username,  "password", oda_password), file = "~/.authinfo")
          saspy_path <- paste0(gsub("Location: ", "", system(paste(reticulate::virtualenv_python("r-reticulate"), "-m pip show saspy"), intern = TRUE)[8]), "/saspy")
          cat("SAS_config_names = ['oda']
          
          oda = {
              'java' : '/usr/bin/java',
              'iomhost' : ['odaws01-usw2-2.oda.sas.com','odaws02-usw2-2.oda.sas.com'],
              'iomport' : 8591,
              'encoding' : 'utf-8',
              'authkey' : 'oda'
          }", file = paste0(saspy_path, "/sascfg_personal.py"))
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
